### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by EmergentOrder** [Ldpe2G/AC-BLSTM#2]
@Ldpe2G I was just wondering: do you maybe have some updates you could push here, specifically to bring compatibility with more recent versions of MXNet? Thanks for providing this repo!

**Comment by Ldpe2G** [comment]
@EmergentOrder I will refine the project this weekend.

**Comment by Ldpe2G** [comment]
@EmergentOrder update to the lastest mxnet version, have a try

**Comment by EmergentOrder** [comment]
Awesome, thanks! It looks like it is working now, but I had to make two small changes first: 
Specify the sbt version (since my local version is newer, for example), and update the package name for MXNet (has changed, from ml.dmlc.mxnet to org.apache.mxnet).
I put those in a PR

**Comment by EmergentOrder** [comment]
actually I see that they just today reverted the namespace (package name) change, although they will reintroduce it at some point... you can just leave my PR open for now, until they finalize the namespace change
